### ISSUE TITLE
MarketCatalogue model uses the same fields as MarketFilter

### ISSUE THREAD

**Issue by Huweey** [tiagojsrios/betfair-client-csharp#2]
Hi, 

First off, I like your client, it's much cleaner than anything else I've found, and also on newer tech.

I noticed the MarketCatalogue model has the wrong properties, it has the same properties as the MarketFilter.

**MarketCatalogue:** https://github.com/tiagojsrios/betfair-client-csharp/blob/main/src/BetfairClient/BetfairClient.Models/Betting/MarketCatalogue.cs

**MarketFilter:** https://github.com/tiagojsrios/betfair-client-csharp/blob/main/src/BetfairClient/BetfairClient.Models/Betting/MarketFilter.cs

I'm happy to contribute if you need anything.

Cheers, 
Huw

**Comment by tiagojsrios** [comment]
Hello @Huweey,

First of all, thanks for your report and offering yourself to contribute. I'm already working on the fix, and I'll publish a new version soon. 

I'm quite surprised seeing people using the library. I'll make sure that I put some hours on improving the client, as I have some ideas. Thank you for the comment.

**Comment by tiagojsrios** [comment]
You can now download the new version @Huweey. https://www.nuget.org/packages/BetfairClient/1.0.7

Do let me know if you find any other issue!

**Comment by Huweey** [comment]
That's great thank you, I look forward to your new version.

I had my own client implemented but was curious if there was something more complete out there. However, as you probably know, the C# examples on the Betfair documentation are pretty out of date so it's definitely worth maintaining this in my opinion.
