### ISSUE TITLE
GetListMarketBook has wrong return type

### ISSUE THREAD

**Issue by Huweey** [tiagojsrios/betfair-client-csharp#3]
Hi,

I've just given 1.0.7 a look and GetListMarketBook is returning an IEnummerable of MarketCatalogue rather than MarketBook.

I can't see any other problems although I haven't implemented the full API yet.

Cheers,
Huw

**Comment by tiagojsrios** [comment]
Hello,

Thanks for the issue report. I have just published a [new version](https://www.nuget.org/packages/BetfairClient/1.0.8) with this fix. I found out there actually were more methods with wrong return type, so I also fixed those.

Starting from tomorrow, I will put some effort again on improving this library. As my first task, I will look through all methods and return types, to see if everything is correct. Thanks for your help.

Cheers!
