### ISSUE TITLE
Data fields

### ISSUE THREAD

**Issue by Huweey** [tiagojsrios/betfair-client-csharp#4]
Hi again,

I've noticed a couple of problems, I thought I'd raise them here rather than a separate thread each time as they are quite small.

**RunnerCatalog**
- The RunnnerName property name should only have 2 'n's 

**MarketDescription**
- The TurnInplayEnabled property is a DateTime but should be a boolean

**LimitOrder**
- timeInForce, minFillSize, betTargetType, betTargetSize these properties are optional and therefore I think should be nullable, certainly the enums need to be nullable otherwise they default to unwanted values.

**PlaceExecutionReport**
- errorCode should be nullable otherwise it defaults to unwanted values.

**PlaceInstructionReport** 
- errorCode, OrderStatus should be nullable otherwise it defaults to unwanted values.
- The betId, placedDate, averagePriceMatched, sizeMatched fields are missing.

Thanks

**Comment by tiagojsrios** [comment]
Hello.

Thanks for your report. I've just fixed those issues and released a [new version](https://www.nuget.org/packages/BetfairClient/1.0.9) of the NuGet.

As a first step, I'm currently doing some kind of maintenance (checking if all models are correct, etc). I've been working on a [feature/maintenance branch](https://github.com/tiagojsrios/betfair-client-csharp/tree/feature/maintenance). I hope to push this to the main branch soon!

Cheers
